### ISSUE TITLE
Adding multi-tenancy properties to deployment.yaml

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/docs-apim#1276]
**Description:**
With the patch 'WSO2-CARBON-PATCH-4.6.0-0072' following can be configured in deployment.yaml. Shall we add this to docs.

```toml
[multi_tenancy.billing.package.demo]
name = "Demo"
subscription_charge = 0
    [multi_tenancy.billing.package.demo.users]
    limit= "1"
    charge= "0"
    [multi_tenancy.billing.package.demo.resource_volume]
    limit= "20"
    overuse_charge= "0"
    [multi_tenancy.billing.package.demo.bandwidth]
    limit= "50"
    overuse_charge= "0"

[multi_tenancy.billing.package.smb]
name = "SMB"
subscription_charge = "100"
    [multi_tenancy.billing.package.smb.users]
    limit= "unlimited"
    charge= "0"
    [multi_tenancy.billing.package.smb.resource_volume]
    limit= "50"
    overuse_charge= "0"
    [multi_tenancy.billing.package.smb.bandwidth]
    limit= "150"
    overuse_charge= "0"

[[multi_tenancy.billing.package.custom]]
name = "Professional"
subscription_charge = "500"
    [[multi_tenancy.billing.package.custom.users]]
    limit = "unlimited"
    charge = "0"
    [[multi_tenancy.billing.package.custom.resource_volume]]
    limit = "500"
    overuse_charge = "0"
    [[multi_tenancy.billing.package.custom.bandwidth]]
    limit = "1536"
    overuse_charge = "0.03"

[[multi_tenancy.billing.package.custom]]
name = "Enterprise"
subscription_charge = "2000"
    [[multi_tenancy.billing.package.custom.users]]
    limit = "unlimited"
    charge = "0"
    [[multi_tenancy.billing.package.custom.resource_volume]]
    limit = "5120"
    overuse_charge = "0"
    [[multi_tenancy.billing.package.custom.bandwidth]]
    limit = "15360"
    overuse_charge = "0.02"

[multi_tenancy.usage_agent.data_persistence_task]
startup_delay_in_ms = "60000"
records_per_execution = "100"
execution_interval_in_ms = "-1"

[[multi_tenancy.throttling_manager_tasks]]
data_providers = [
    "org.wso2.carbon.throttling.manager.dataproviders.BillingDataProvider",
    "org.wso2.carbon.throttling.manager.dataproviders.UsageDataProvider"
]
    [multi_tenancy.throttling_manager_tasks.parameters]
    interval = "10"
    "delay" = "60"

[multi_tenancy.stratos]
disable_tenant_management_emails = true
email_validation_mandatory_for_login = false
tenant_activation_moderated = false
super_admin_email = "super-admin-email"
skip_summary_generator = false
notification_email = "notification-email"
finance_notification_email = "finance-notification-email"
charge_on_registration = false
public_cloud_setup = true
google_analytics_url = "http://google-analytics.js"
sso_loading_message = "Loading..."
    [multi_tenancy.stratos.paypal]
    url = "Paypal URL"
    username = "username"
    password = "password"
    signature = "signature"
    environment = "live"
    [multi_tenancy.stratos.manager_service]
    url = "https://cloud-test.wso2.com/services/"
    admin_username = "admin"
    admin_password = "admin"

[[multi_tenancy.cloud_services]]
name = "WSO2 API Manager"
default = true
key = "AM"
label = "API Manager"
link = "https://am.cloud.wso2.com"
description = "API Manager in the cloud"
```
