### ISSUE TITLE
Missing Configuration in the "Configure WSO2 IS as a Key Manager" documentation

### ISSUE THREAD

**Issue by Prabhashi** [wso2/docs-apim#2119]
**Description:**

I was following this documentation[1] to configure WSO2 IS as KM with WSO2 API Manager 3.2.0. But when trying to change the ownership of an application I encounter the following issue.

```
[2020-10-22 17:31:53,249] ERROR - AbstractKeyManager Error occurred while updating OAuth Client :
org.wso2.carbon.apimgt.impl.kmclient.KeyManagerClientException: Received status code: 401 Reason:
```

I was able to overcome this issue by adding the below configuration to the deployment.toml file of the WSO2 IS.

```
[[resource.access_control]]
context = "(.*)/keymanager-operations/dcr/register(.*)"
secure = true
http_method = "POST"
permissions = "/permission/admin/manage/identity/applicationmgt/update"
scopes = "internal_application_mgt_update"
```

[1] https://apim.docs.wso2.com/en/latest/administer/key-managers/configure-wso2is-connector/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
APIM 3.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by athiththan11** [comment]
Hi Team

The same configurations need to be added in the following Doc space as well [[1]](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager/#step-4-configure-wso2-is-with-wso2-api-m) (Step 04 -> Point 4).

```toml
[[resource.access_control]]
context = "(.*)/keymanager-operations/dcr/register(.*)"
secure = true
http_method = "PUT"
permissions = "/permission/admin/manage/identity/applicationmgt/update"
scopes = "internal_application_mgt_update"

[[resource.access_control]]
context = "(.)/keymanager-operations/dcr/register(.)"
secure = true
http_method = "POST"
permissions = "/permission/admin/manage/identity/applicationmgt/update"
scopes = "internal_application_mgt_update"
```

[1] [https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager/](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager/)
