### ISSUE TITLE
Fix the documentation error for controller in apictl 3.0  and 2.0

### ISSUE THREAD

**Issue by 1akshitha** [wso2/docs-apim#3060]
**Description:**
In the API CTL docs of APICTL 3.0[1] and 2.0.13[2], the api_param.yaml key related to certificate host name has to be updated. Currently the structure of the parameter file is listed as follows. 
```environments:
    - name: <environment_name>
      endpoints:
          production:
              url: <production_endpoint_url>
              config:
                  retryTimeOut: <no_of_retries_before_suspension>
                  retryDelay: <retry_delay_in_ms>
                  factor: <suspension_factor>
          sandbox:
              url: <sandbox_endpoint_url>
              config:
                  retryTimeOut: <no_of_retries_before_suspension>
                  retryDelay: <retry_delay_in_ms>
                  factor: <suspension_factor>
      gatewayEnvironments:
        - <gateway_environment_name>           
      certs:
        - hostName: <endpoint_url>
          alias: <certificate_alias>
          path: <certificate_file_path>
```

It has to be updated to 
```
environments:
    - name: <environment_name>
      endpoints:
          production:
              url: <production_endpoint_url>
              config:
                  retryTimeOut: <no_of_retries_before_suspension>
                  retryDelay: <retry_delay_in_ms>
                  factor: <suspension_factor>
          sandbox:
              url: <sandbox_endpoint_url>
              config:
                  retryTimeOut: <no_of_retries_before_suspension>
                  retryDelay: <retry_delay_in_ms>
                  factor: <suspension_factor>
      gatewayEnvironments:
        - <gateway_environment_name>           
      certs:
        - host: <endpoint_url>
          alias: <certificate_alias>
          path: <certificate_file_path>
```
If the api_params.json file is used, we can use the hostName key. However since we are not mentioning anything about a json params file, we can omit that. We have to update the examples as well.

This has been fixed in the product from APICTL 3.1 onwards.

[1] - https://apim.docs.wso2.com/en/3.0.0/learn/api-controller/advanced-topics/configuring-environment-specific-parameters/
[2]- https://docs.wso2.com/display/AM260/Building+CICD+Pipeline#BuildingCICDPipeline-ImportingEndpointCertificates
