### ISSUE TITLE
[Doc] Incorrect configuration in K8 operator sample

### ISSUE THREAD

**Issue by sachithKay** [wso2/docs-apim#3368]
**Description:**
Sample yaml configuration given in step 4 of the (https://apim.docs.wso2.com/en/next/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-integration/integration-deployments/) doc should be corrected  as following
- secretKeyRef --> secretRef
```
envFrom:
    - configMapRef:
        name: CONFIG_MAP_NAME
    - secretKeyRef:
        name: SECRET_NAME  
```
