### ISSUE TITLE
Rename the default gateway environment "Production and Sandbox" to "Default"

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#3505]
**Description:**
Fix the following in the documentation.

Current default config:

```toml
[[apim.gateway.environment]]
name = "Production and Sandbox"

```
Expected Config:
```toml
[[apim.gateway.environment]]
name = "Default"

```

**Related Issues:**
https://github.com/wso2/product-apim/issues/10477
