### ISSUE TITLE
[3.2.0] Update API Key Docs with Keystore Configurations

### ISSUE THREAD

**Issue by athiththan11** [wso2/docs-apim#3550]
**Description:**

As default the API Manager v3.2.0 uses the Primary Keystore to Sign the API Keys when generating it from the Devportal. But, it is also possible to configure a custom Keystore or any other Keystore configured in the `carbon.xml` to use and sign the tokens. The Docs related to [API Keys](https://apim.docs.wso2.com/en/latest/learn/api-security/api-authentication/secure-apis-using-api-keys/#changing-the-alias-name-in-the-jwt) contains the configurations related to only changing the Certificat Alias name.

Hence, the Docs needs to be updated with the configurations to configure a custom Keystore or any to use the certs and to sign the API Key tokens. Following is a sample configuration to configure a Keystore for the API Key signing

```toml
[apim.devportal]
api_key_keystore = "APIKeyKeyStore" #the name of the Keystore is picked from the carbon.xml
```

**Affected Product Version:**

- API Manager v3.2.0
