### ISSUE TITLE
[SI] Missing steps in `Quick Start Guide - Streaming Integration`

### ISSUE THREAD

**Issue by senthuran16** [wso2/docs-apim#5320]
**Description:**
The following points are missing from [**Quick Start Guide - Streaming Integration**](https://apim.docs.wso2.com/en/latest/get-started/streaming-quick-start-guide/#!).

The following changes should be mentioned under the topic **Exposing an Streaming Service as a Managed API**

1. Indentation of the `service.catalog.configs` section should be corrected as follows:
```
service.catalog.configs:
    enabled: true
    hostname: localhost
    port: 9444
    username: admin
    password: admin
```
The `9444` port shown above is the port of API Manager, to which, the service catalog listens.

2. Just after the above point, information about adding an Async API spec to a Siddhi app, and deploying it to the service catalog should be provided. Please refer [this](https://apim.docs.wso2.com/en/latest/use-cases/streaming-tutorials/expose-a-kafka-topic-as-a-managed-websocket-api/#step-4-generate-an-asyncapi-definition) for the steps.
