### ISSUE TITLE
Update MI certificate revocation configs

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/docs-apim#5372]
**Description:**
We need to update the Passthrough listener config as follows in [Verifying certificate revocation](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/mi-setup/transport_configurations/configuring-transports/#verifying-certificate-revocation). 
- We have missed adding the `listener.verify_client = "require"` parameter to [transport.http] config.

```toml
[transport.http]
listener.certificate_revocation_verifier_enable = true
listener.certificate_revocation_cache_size = 1024
listener.certificate_revocation_cache_delay = 1000
listener.verify_client = "require"
```
- Explicitly state that the client needs to send its own public certificate to MI when certificate revocation is enabled in the listener.

**Affected Product Version:**
MI 4.0.0, MI 4.1.0
