### ISSUE TITLE
Update the sample toml in the Tuning the Kafka inbound section in MI

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/docs-apim#5383]
**Description:**
The sample toml configuration in [1] should be changed as follows, (the mediation tag should contain only a single opening and closing square brackets)
```toml
[mediation]
inbound.core_threads = 200 
inbound.max_threads = 1000
```

[1]-https://apim.docs.wso2.com/en/latest/install-and-setup/setup/mi-setup/performance_tuning/tuning-inbound-endpoints/#tuning-the-kafka-inbound

**Affected Product Version:**
MI 4.0.0 and above
