### ISSUE TITLE
Configure Choreo Connect Truststore with Helm Chart

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/docs-apim#6711]
**Description:**
The documentation on configuring truststore should include, the K8s secret should be created in the cluster first and then the file is mounted with auto-generated name, which can be replaced with `mountAs` as in the helm chart.
https://apim.docs.wso2.com/en/4.1.0/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline/#configuring-truststore

Steps that can be suggested to someone to successfully mount, and configure Choreo Connect.

1. Create a k8s secret with the cert.
2. Update values.yaml of the helm chart under enforcer.security.truststore with the secretName and subPath created in step 1.
3. Exec into enforcer pod to validate the cert files are mounted correctly. (inside /home/wso2/security/truststore)
4. Copy the file name of the cert (Helm chart will rename the file as "<secretName>-<subPath replace '.' with '-' >.pem")
5. Update the ConfigToml with the correct cert file names copied in step 4.

**Versions**
Applicable for CC 1.0.0, CC 1.1.0

**Related Issues:**
https://github.com/wso2/kubernetes-microgateway/issues/97

**Comment by renuka-fernando** [comment]
The cert can be renamed by setting `mountAs`.

```yaml
# Truststore certs as an array of secrets {secretName, subPath, mountAs}
# override default certs from secrets
truststore:
  - # Name of the secret
    secretName: "control-plane-cert"
    # Key name of the secret
    subPath: "tls.crt"
    # Optional file name to mount the secret with the given name inside the container.
    # Default to auto-generated file name `{secretName}-{subPath | replace "." with "-"}.pem`.
    # Auto-generated file name for this sample: "control-plane-cert-tls-crt.pem"
    mountAs: "controlplane.pem"
```
