### ISSUE TITLE
Missing information for Solace External Broker and Gateway Integration with API Manager

### ISSUE THREAD

**Issue by senthuran16** [wso2/docs-apim#7764]
**Description:**
$Subject, at https://apim.docs.wso2.com/en/4.3.0/tutorials/integrating-with-solace/.

Information about how to obtain the following from Solace, are not available.
```toml
    [[apim.gateway.environment]]
    name = <Name of the Solace Environment>
    display_name = <Display Name of the Solace Environment>
    type = <Type of the Environment>
    display_in_api_console = <Displays the environment under 'Try it' in the API Developer Portal, in the API console>
    description = <Description about Solace Environment>
    provider = <Vendor name of the environment. (Must be "solace")>
    service_url = <Base URL of the Solace broker>
    username = <Username of the Solace broker account>
    password = <Password of the Solace broker account>
    ws_endpoint = <WS Endpoint of the Solace broker environment>
    wss_endpoint = <WSS Endpoint of the Solace broker environment>
    http_endpoint = <HTTP Endpoint of the Solace broker environment>
    https_endpoint = <HTTPS Endpoint of the Solace broker environment>
    show_as_token_endpoint_url = false

    [apim.gateway.environment.properties]
    Organization = <Organization created in Solace>
    DevAccountName = <Solace Broker email ID>

```
