### ISSUE TITLE
Remove 'UserPortalDataMigrator' steps from the APIM migration document

### ISSUE THREAD

**Issue by sanethmaduranga** [wso2/docs-apim#7901]
**Description:**
The APIM migration document contains the '_**Step 3**_' which is related to the identity components migration of the APIM server.
There we are removing a set of unwanted migration steps when the migration process is based on the APIM servers(Not the WSO2-IS servers as the key-manager).
In that, under the '_**Remove the following 3 steps from migration-config.yaml, which are included under version: "5.11.0".**_' section, we are removing a set of migration steps.
Under the same section, we need to add the below steps as removal steps.

```
 - name: "UserPortalDataMigrator"
  order: 9
  parameters:
    location: "step4"
    schema: "identity"
- name: "UserPortalDataMigrator"
  order: 10
  parameters:
    location: "step4"
    schema: "um"
```

**Suggested Labels:**
migration, migration-to-4.0.0, migration-to-4.1.0, migration-to-4.2.0

**Affected Product Version:** APIM-4.0.0, APIM-4.1.0, APIM-4.2.0

**Related Issues:**
https://github.com/wso2-enterprise/wso2-apim-internal/issues/5335
