### ISSUE TITLE
Update JSON Schema Validator Documentation with 'additionalProperties' Configuration

### ISSUE THREAD

**Issue by npamudika** [wso2/docs-apim#7964]
**Description:**
Response validation is not working correctly when using the following schema in the API definition.

```
schema:
    required:
        - Items Inventory
    type: object
    properties:
        Items Inventory:
            type: array
            items:
                type: object
                properties:
                    id_businesscom:
                        type: string
                    id_customer:
                        type: string
                    qty_purch_order:
                        type: number
                    last_purch_order:
                        type: string
                    next_delivery:
                        type: string
                    not_deliverable:
                        type: boolean
                    inventory_in_pieces_Total:
                        type: number
                    gtin:
                        type: string
```

The reason is that the following request is accepted by the API, even though there are some properties in the request that were not specified in the above schema.

```
{
    "Items Inventory": [
        {
            "id_businesscom": "234.895.AA",
            "id_customer": "",
            "qty_purch_order": 0.0,
            "last_purch_order": "",
            "next_delivery": "",
            "not_deliverable": false,
            "inventory_in_pieces_Total": 29.0,
            "inventory_in_pieces_B2B": 29.0,
            "inventory_in_pieces_B2C": 0,
            "gtin": "8099999999999"
        }
    ]
}
```

Solution is to use the above schema with 'additionalProperties: false' as follows, in order to prevent the acceptance of additional properties other than those specified in the schema.

```
schema:
    required:
        - Items Inventory
    type: object
    properties:
        Items Inventory:
            type: array
            items:
                type: object
                properties:
                    id_businesscom:
                        type: string
                    id_customer:
                        type: string
                    qty_purch_order:
                        type: number
                    last_purch_order:
                        type: string
                    next_delivery:
                        type: string
                    not_deliverable:
                        type: boolean
                    inventory_in_pieces_Total:
                        type: number
                    gtin:
                        type: string
                additionalProperties: false
```

Add 'additionalProperties' configuration in the documentation[1] along with a yaml format example, as this is a common requirement.

[1] https://apim.docs.wso2.com/en/4.1.0/design/api-security/api-request-response-schema-validation/json-schema-validator/#enabling-the-json-schema-validator
