### ISSUE TITLE
CustomParameters values not setting

### ISSUE THREAD

**Issue by Vsetecka7** [wso2/docs-apim#8486]
Location : https://apim.docs.wso2.com/en/3.2.0/learn/api-controller/advanced-topics/configuring-different-endpoint-security-types/

I have a issue with customParameter attribute (scope: test). However i set any key-value pairs, I still don't see them in the endpoint.

Here is part of my **api.yaml** downloaded from apim after setting parameter manually in GUI:
```
  endpointConfig:
    endpoint_type: http
    endpoint_security:
      production:
        tokenUrl: https://apim.cz/apitest/rest/v1/auth/oauth2/token
        clientId: testId
        clientSecret: testSecret
        customParameters:
          scope: test
        additionalProperties: {}
        type: OAUTH
        grantType: CLIENT_CREDENTIALS
        enabled: true
```
When I try to use the exact same yaml for update (via apictl 4.0), It doesn't set the value, and the downloaded **api.yaml** looks like this: ```customParameters: {}```
